config/routes.rb
Rails.application.routes.draw do
  resources :books

  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all.order(title: :desc)
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notuce: "You've added a new book"
    else
      render :new
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path, notice: 'The book is deleted'
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      redner :edit
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.haml
= simple_form_for @book, html: {multipart: true} do |f|
  - if @book.errors.any?
    #errors
      %p
        = @book.errors.count
        Prevented this book from saving
      %ul
        - @book.errors.full_messeges.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit, class: 'btn btn-primary'

app/views/books/edit.html.haml
%h2 Edit the book

= render 'form'

= link_to 'Back', root_path

app/views/books/index.html.haml
%h1 Books
- @books.each do |book|
  %h3= link_to book.title, book

app/views/books/new.html.haml
%h2 Add your book

= render 'form'

%br/

= link_to 'Back', root_path

app/views/books/show.html.haml
%h1= @book.title
%p= @book.description

= link_to 'Back', root_path
= link_to 'Edit', edit_book_path(@book)
= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: 'Really wanna delete this book?'}

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title BookBox
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield